### ISSUE TITLE
proposta de melhoria nas rotas

### ISSUE THREAD

**Issue by Tcalura** [brunojppb/rails_contact_list#1]
Bruno, tudo bem ? 

Voce pode escrever as rotas users e contacts dizendo apenas as que não quer, da seguinte forma:
```
  resources :users, except: %i[index destroy] do
    resources :contacts, except: :show
  end
```

**Comment by brunojppb** [comment]
Olá @Tcalura,
Obrigado pela sugestão.
Em minha opinião, a forma atual é mais explicita. Olhando para o arquivo de `routes.rb`, eu vejo de rapidamente as rotas disponíveis. Porém isso é a penas a forma que prefiro.
Sua sugestão também é uma solução muito boa.
